service: youtube-api
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

function:
  youtubeFn:
    handler: hello.handler
    events:
      - http:
          path: /hello
          method: GET
          cors: true
